# Copyright (c) 2015 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#
#
description: Apps and Engines related to Asset based work.

#################################################################################################
# include common files

includes:
# launchers for launching DCCs such as Maya, Nuke etc.
- ./includes/app_launchers.yml
# common app configurations that are reused across environments
- ./includes/common_apps.yml

- ./steps/maya2016_model.yml
- ./steps/3dsmax.yml
- ./steps/mari3.yml
- ./steps/photoshop.yml

#################################################################################################
# define all the items that should appear in this environment

engines:
  #
  # -------------------------------------------------
  # 3dsmax Plus
  # -------------------------------------------------
  tk-3dsmaxplus: '@3dsmaxplus'

  #
  # -------------------------------------------------
  # Mari
  # -------------------------------------------------
  tk-mari: '@mari'
  #
  # -------------------------------------------------
  # Maya
  # -------------------------------------------------
  tk-maya: '@maya_model'

  
  #
  # -------------------------------------------------
  # Photoshop
  # -------------------------------------------------
  tk-photoshop: '@photoshop'
    
  #
  # -------------------------------------------------
  # Shell Engine (tank command)
  # -------------------------------------------------
  tk-shell:
    apps:
      tk-multi-launch3dsmax: '@launch_3dsmax'
      tk-multi-launchmari: '@launch_mari'
      tk-multi-launchmaya: '@launch_maya'
      tk-multi-launchphotoshop: '@launch_photoshop'
      tk-multi-screeningroom: '@launch_screeningroom'
    location:
      version: v0.5.1
      type: app_store
      name: tk-shell

#
###############################################################################
#
# Framework includes.
#
# Frameworks are libraries that are shared between apps and that contain
# common functionality for building UIs and communicating with Shotgun.
# Frameworks are automatically installed when apps are installed and udpated.
#
frameworks: null