# Shotgun Pipeline Toolkit configuration file
# This file was automatically created by setup_project
# This file reflects the paths in the primary pipeline
# configuration defined for this project.

Windows: 'w:\apps\shared\robotsgtk\current'
Darwin: '/apps/shared/robotsgtk/current'
Linux: '/apps/shared/robotsgtk/current'

# End of file.
