#################################################################################################
# include common files

includes:
# launchers for launching DCCs such as Maya, Nuke etc.
- ../includes/app_launchers.yml
# common app configurations that are reused across environments
- ../includes/common_apps.yml

# maya asset step configs
  
maya_model:
    apps:
      tk-multi-about: '@about'
      tk-multi-breakdown:
        hook_scene_operations: '{self}/tk-maya_scene_operations.py'
        location:
          version: v1.4.4
          type: app_store
          name: tk-multi-breakdown
      tk-multi-loader2:
        action_mappings:
          Maya Scene: [reference, import]
          Alembic Cache: [reference, import]
          Photoshop Image: [texture_node]
          Rendered Image: [texture_node]
          UDIM Image: [udim_texture_node]
        actions_hook: '{self}/tk-maya_actions.py'
        download_thumbnails: true
        entities:
        - caption: Assets
          entity_type: Asset
          filters:
          - [project, is, '{context.project}']
          hierarchy: [sg_asset_type, code]
        - caption: My Tasks
          entity_type: Task
          filters:
          - [task_assignees, is, '{context.user}']
          - [project, is, '{context.project}']
          hierarchy: [entity, content]
        filter_publishes_hook: '{self}/filter_publishes.py'
        location:
          version: v1.11.3
          type: app_store
          name: tk-multi-loader2
        menu_name: Load
        publish_filters: []
        title_name: Loader
      tk-multi-publish:
        allow_taskless_publishes: true
        display_name: Publish
        expand_single_items: false
        hook_copy_file: default
        hook_post_publish: default
        hook_primary_pre_publish: default
        hook_primary_publish: default
        hook_scan_scene: default
        hook_secondary_pre_publish: default
        hook_secondary_publish: default
        hook_thumbnail: default
        location:
          version: v0.9.4
          type: app_store
          name: tk-multi-publish
        primary_description: Publish and version up the current Maya scene
        primary_display_name: Maya Publish
        primary_icon: icons/publish_maya_main.png
        primary_publish_template: maya_asset_publish
        primary_scene_item_type: work_file
        primary_tank_type: Maya Scene
        secondary_outputs:
        - description: Publish Asset Alembic data 
          display_group: Geometry Caches
          display_name: Alembic Caches
          icon: icons/alembic_cache_publish.png
          name: alembic_cache
          publish_template: asset_alembic_publish
          required: false
          scene_item_type: geometry
          selected: false
          tank_type: Alembic Cache
          
        - description: Publish Asset GPU Cache
          display_group: Geometry Caches
          display_name: GPU Cache
          icon: icons/alembic_cache_publish.png
          name: gpu_cache
          publish_template: asset_gpu_cache_publish
          required: false
          scene_item_type: geometry
          selected: false
          tank_type: GPU Cache
        template_work: maya_asset_work
      tk-multi-screeningroom: '@launch_screeningroom'
      tk-multi-shotgunpanel:
        action_mappings:
          PublishedFile:
          - actions: [reference, import]
            filters: {published_file_type: Maya Scene}
          - actions: [reference, import]
            filters: {published_file_type: Alembic Cache}
          - actions: [texture_node]
            filters: {published_file_type: Rendered Image}
          - actions: [texture_node]
            filters: {published_file_type: Photoshop Image}
          - actions: [udim_texture_node]
            filters: {published_file_type: UDIM Image}
          Task:
          - actions: [assign_task, task_to_ip]
            filters: {}
        actions_hook: '{self}/general_actions.py:{self}/tk-maya_actions.py'
        location:
          version: v1.2.11
          type: app_store
          name: tk-multi-shotgunpanel
        shotgun_fields_hook: '{self}/shotgun_fields.py'
      tk-multi-snapshot:
        hook_copy_file: default
        hook_scene_operation: default
        hook_thumbnail: default
        location:
          version: v0.6.1
          type: app_store
          name: tk-multi-snapshot
        template_snapshot: maya_asset_snapshot
        template_work: maya_asset_work
      tk-multi-workfiles2:
        allow_task_creation: true
        create_new_task_hook: default
        custom_actions_hook: default
        entities:
        - caption: Assets
          entity_type: Task
          filters:
          - [entity, type_is, Asset]
          hierarchy: [entity.Asset.sg_asset_type, entity, step, content]
        - caption: Shots
          entity_type: Task
          filters:
          - [entity, type_is, Shot]
          hierarchy: [entity.Shot.sg_sequence, entity, step, content]
        file_extensions: []
        hook_copy_file: default
        hook_filter_publishes: default
        hook_filter_work_files: default
        hook_scene_operation: default
        launch_at_startup: false
        location:
          version: v0.7.42
          type: app_store
          name: tk-multi-workfiles2
        my_tasks_extra_display_fields: []
        saveas_default_name: scene
        saveas_prefer_version_up: false
        show_my_tasks: true
        template_publish: maya_asset_publish
        template_publish_area: asset_publish_area_maya
        template_work: maya_asset_work
        template_work_area: asset_work_area_maya
        version_compare_ignore_fields: []
    compatibility_dialog_min_version: 2015
    debug_logging: false
    location:
      version: v0.7.6
      type: app_store
      name: tk-maya
    menu_favourites:
    - {app_instance: tk-multi-workfiles2, name: File Open...}
    - {app_instance: tk-multi-snapshot, name: Snapshot...}
    - {app_instance: tk-multi-workfiles2, name: File Save...}
    - {app_instance: tk-multi-publish, name: Publish...}
    template_project: asset_work_area_maya
    use_sgtk_as_menu_name: false